version: '2'
services:
    elasticsearch:
        labels:
            io.rancher.scheduler.affinity:container_label_soft_ne: io.rancher.stack_service.name=$${stack_name}/$${service_name}
            io.rancher.container.hostname_override: container_name
            io.rancher.sidekicks: es-storage
            {{- if eq .Values.UPDATE_SYSCTL "true" -}}
                ,es-sysctl
            {{- end}}
        image: docker.elastic.co/elasticsearch/elasticsearch-platinum:6.2.2 
        environment:
            - "cluster.name=${cluster_name}"
            - "node.name=$${HOSTNAME}"
            - "bootstrap.memory_lock=true"
            - "xpack.security.enabled=false"
            - "ES_JAVA_OPTS=-Xms${node_heap_size} -Xmx${node_heap_size}"
            - "discovery.type=single-node"
            - "xpack.ml.enabled=true"
            - "ELASTIC_PASSWORD=MagicWord"
        ports:
            - 9200:9200
            - 9300:9300
        ulimits:
            memlock:
                soft: -1
                hard: -1
            nofile:
                soft: 65536
                hard: 65536
        mem_limit: ${node_mem_limit}
        mem_swappiness: 0
        cap_add:
            - IPC_LOCK
        volumes_from:
            - es-storage

    kibana:
      image: docker.elastic.co/kibana/kibana:6.2.2 
      external_links:
        - elasticsearch:elasticsearch
      environment:
        - ELASTICSEARCH_URL=http://elasticsearch:9200
      ports: 
        - 5601:5601
      depends_on:
        elasticsearch
    es-storage:
        labels:
            io.rancher.container.start_once: true
        network_mode: none
        image: rawmind/alpine-volume:0.0.2-2
        environment:
            - SERVICE_UID=1000
            - SERVICE_GID=1000
            - SERVICE_VOLUME=/usr/share/elasticsearch/data
        volumes:
            - es-storage-volume:/usr/share/elasticsearch/data

    {{- if eq .Values.UPDATE_SYSCTL "true" }}
    es-sysctl:
        labels:
            io.rancher.container.start_once: true
        network_mode: none
        image: rawmind/alpine-sysctl:0.1-1
        privileged: true
        environment:
            - "SYSCTL_KEY=vm.max_map_count"
            - "SYSCTL_VALUE=262144"
    {{- end}}


volumes:
  es-storage-volume:
    driver: ${VOLUME_DRIVER}
    per_container: true
