version: '2'
catalog:
    name: Elasticsearch Platinum SingleNode 6.2.2
    version: 6.2.2-p-singlenode
    description: Non-Scalable Elasticsearch Cluster

    questions:
        - variable: "cluster_name"
          type: "string"
          required: true
          label: "Cluster name"
          description: "Name of the Elasticsearch Cluster"
          default: "es-cluster"

        - variable: "UPDATE_SYSCTL"
          label: "Update host sysctl:"
          description: |
            Set true to avoid vm.max_map_count errors.
            WARN: If set true, host param vm.max_map_count will be update to 262144.
          default: true
          required: true
          type: enum
          options:
            - false
            - true

        - variable: "node_heap_size"
          type: "string"
          required: true
          label: "Heap size"
          description: "Heap size to be allocated for Java"
          default: "512m"

        - variable: "node_mem_limit"
          type: "int"
          required: true
          label: "Memory limit in byte"
          description: "Memory limit in Byte per elasticsearch container. AT LEAST double the heap size!"
          default: 1073741824

        - variable: "VOLUME_DRIVER"
          description: "The VOLUME driver to associate with this server"
          label: "VOLUME Driver"
          required: true
          default: "local"
          type: enum
          options:
            - local
            - rancher-nfs
            - rancher-efs
            - rancher-ebs

services:

  elasticsearch:
    scale: 1

  kibana:
    scale: 1
    scale: 1
