version: '2'
services:
    kibana:
        image: docker.elastic.co/kibana/kibana:6.2.2 
        environment:
            - ELASTICSEARCH_URL=http://es-master:9200
        ports: 
          - 5601:5601
