version: '2'
services:
    kibana:
        image: docker.elastic.co/kibana/kibana:6.2.2 
        environment:
            - elasticsearch.ur;=http://ubuntuserver.local:9200
            - "ELASTIC_PASSWORD=MagicWord"
