version: '2'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.2 
    external_links:
      - ${elasticsearch_source}:elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    ports: 
      - 5601:5601
